theme: jekyll-theme-hacker
title: gr33pp💀machine:~#
description: Curiosity.
show_downloads: false
show_repo: false

safe: true

plugins:
- jekyll-sitemap
gems:
- jekyll-sitemap
whitelist:
- jekyll-sitemap

